package domain

import "errors"

var (
	ErrActivityNotFound          = errors.New("failed to get activity under given activity name")
	ErrActivityIDNotFound        = errors.New("failed to get activity ID")
	ErrActivitySearchURLNotFound = errors.New("failed to get activity-search URL")
	ErrIncidentURLNotFound       = errors.New("failed to get URL for getting incidents")
	ErrInvalidTab                = errors.New("failed to get manager tab")
	ModificationURLNotFound      = errors.New("failed to get URL for modification")
	ErrNoActivityFound           = errors.New("failed to get any activities")
	ErrNoDataFound               = errors.New("failed to get any processes on given client")
	ErrNoIncidentFound           = errors.New("failed to get incident(s)")
	ErrNoRoleFound               = errors.New("failed to fetch roles")
	ErrProcessIDNotFound         = errors.New("failed to get process ID")
	ErrProcessNotFound           = errors.New("failed to get requested processes for given client")
	ErrNoVarsFound               = errors.New("failed to get process variables")
	ErrProcessStatusNotFound     = errors.New("failed to get process status")
	ErrProcessURLNotFound        = errors.New("failed to get process URL")
	ErrProcessesURLNotFound      = errors.New("failed to get processes URL")
	ErrRetriesURLNotFound        = errors.New("failed to get retries URL")
	ErrRoleURLNotFound           = errors.New("failed to get manager role URL")
	ErrTokenNotFound             = errors.New("failed to get token")
	ErrTokenURLNotFound          = errors.New("failed to get token URL")
	ErrUnauthorized              = errors.New("failed to authorize")
	ErrUnknownIncident           = errors.New("couldn't recognize incident type")
	ErrUpdateFailed              = errors.New("couldn't update vars")
	ErrUpdateVarsURLNotFound     = errors.New("failed to get URL for updating vars")
)
